version: "2.2"

services:

# ------> node ------>
    node_1giedmgojlz4azpp:
        container_name: node_1giedmgojlz4azpp
        image: node:alpine
        user: "node"
        working_dir: /node
        volumes:
            - .././:/node
        environment:
            NODE_ENV: dev
        expose:
            - 8081
# <------ node <------